version: "3.9"
services:
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5433"
    environment:
      - POSTGRES_USER=admin1
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=music
  service:
    container_name: server
    build:
      context: .
    expose:
      - 8080
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5433/music
      - DB_USER=admin1
      - DB_PASS=123
      - SERVER_PORT=8080

  nginx:
    build: ./nginx
    ports:
      - "4080:80"
    depends_on:
      - service